Improve shop creator with phpstan
PrestaShop/prestashop-shop-creator pull request #26
Opened 2022-11-03 15:06 UTC by mflasquin

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Improve shop creator with phpstan
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23 
| How to test?      | Launch phpstan locally
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

2022-11-04 07:06 UTC, nicosomb commented on .github/workflows/php.yml
> +        run: ./vendor/bin/phpstan analyse
new line needed 😉

2022-11-04 08:11 UTC, nicosomb submitted a review, later dismissed

2022-11-07 10:44 UTC, lartist commented on .github/workflows/php.yml
> +        with:
```suggestion
        with:
          all_but_latest: true
```

2022-11-09 10:53 UTC, matks requested changes
PR is ok but needs to be rebased to fix git conflicts

Please rebase and ping me and then I will approve ;)

2022-11-09 17:28 UTC, mflasquin commented
> PR is ok but needs to be rebased to fix git conflicts
> 
> Please rebase and ping me and then I will approve ;)

Hi @matks, done :smile:

2022-11-09 19:56 UTC, matks approved these changes

2022-11-09 19:56 UTC, matks commented
Thank you @mflasquin

2022-11-09 19:56 UTC, merged